[browser]
gatherUsageStats = false

[server]
headless = false
port = 8501

[theme]
base = "light"
primaryColor = "#2c3e50"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#2c3e50"